"""initial schema

Revision ID: a72be08cdbbe
Revises: 
Create Date: 2026-06-30 19:24:32.920655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a72be08cdbbe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('game_id', chess_db.types.GUID(length=36), nullable=False),
    sa.Column('white_first_name', sa.String(length=12), nullable=False),
    sa.Column('white_last_name', sa.String(length=12), nullable=False),
    sa.Column('black_first_name', sa.String(length=12), nullable=False),
    sa.Column('black_last_name', sa.String(length=12), nullable=False),
    sa.Column('time_control', sa.String(length=20), nullable=False),
    sa.Column('eval_visible', sa.Boolean(), nullable=False),
    sa.Column('is_live', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('result', sa.Enum('white_wins', 'black_wins', 'draw', 'timeout_white', 'timeout_black', 'incomplete', name='game_result'), server_default=sa.text("'incomplete'"), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_table('moves',
    sa.Column('move_id', chess_db.types.GUID(length=36), nullable=False),
    sa.Column('game_id', chess_db.types.GUID(length=36), nullable=False),
    sa.Column('move_number', sa.Integer(), nullable=False),
    sa.Column('move_notation', sa.String(length=10), nullable=False),
    sa.Column('player', sa.Enum('white', 'black', name='player_color'), nullable=False),
    sa.Column('time_taken_ms', sa.Integer(), nullable=False),
    sa.Column('clock_white_ms', sa.Integer(), nullable=False),
    sa.Column('clock_black_ms', sa.Integer(), nullable=False),
    sa.Column('eval_score', sa.Float(), nullable=True),
    sa.Column('move_quality', sa.String(length=2), nullable=True),
    sa.Column('is_blunder', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('noise_level', sa.Integer(), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('humidity_pct', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('move_id')
    )
    op.create_index('ix_moves_game_id_move_number', 'moves', ['game_id', 'move_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_moves_game_id_move_number', table_name='moves')
    op.drop_table('moves')
    op.drop_table('games')
    # ### end Alembic commands ###
